spring:
  datasource:
    url: jdbc:mysql://localhost:3306/exercise
    username: root
    password: admin123
    tomcat:
      max-idle: 20
      max-active: 50
      max-wait: 20000
  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
    show-sql: true

server:
  port: 8081
rickAndMorty:
  url: 'https://rickandmortyapi.com/api'

feign:
  client:
    config:
      rickAndMortyClient:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: full
        errorDecoder: com.example.aop.mapStruct.exercise.exceptions.CustomErrorDecoder
        #Error: uncomment it when fix successfully
        #requestInterceptors: com.example.aop.mapStruct.exercise.openFeign.client.RickAndMortyClient
  hystrix:
    enabled: true
logging:
  level:
    com.example.aop.mapStruct.exercise.openFeign.client: debug


